# ---------------- MONGODB ----------------
spring.data.mongodb.uri=mongodb+srv://admin1:x6544s@cluster0.qwy1x84.mongodb.net/unifacility?appName=Cluster0
spring.data.mongodb.auto-index-creation=true

# ---------------- SERVER ----------------
server.port=8081